//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboDos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public int IdPersona { get; set; }

        [Display(Name = "NombrePersona ")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        public string NombrePersona { get; set; }


        [Display(Name = "Edad")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        [Range(18, 100, ErrorMessage = "El campo {0} debe estar entre los números {1} y {2}")]
        public Nullable<int> EdadPersona { get; set; }

        [Display(Name = "DescripcionPersona ")]
        [Required(ErrorMessage = "estos campos son requeridos")]
        public string DescripcionPersona { get; set; }
    }
}
